config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :businesses
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :category
  validates :name, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @business = @category.businesses.new()
    render :new
  end

  def show
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @business = @category.businesses.new(business_params)
    @business.phones = params[:phones]
    if @business.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
    @business.update(business_params)
    @business.phones = params[:phones]
    redirect_to category_business_path(@category, @business)
  end

  def destroy
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to category_path(@category)
  end

  private
  def business_params
    params.require(:business).permit(:name, :address, :website, :hours)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.sort_by{|object| object.name.downcase}
    render :index
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new()
    render :new
  end

  def destroy
    @category = Category.find(params[:id])
    @category.businesses.each do |business|
      business.destroy
    end
    @category.destroy()
    redirect_to categories_path
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    render :edit
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/edit.html.erb
<h3>Edit <%=@business.name%></h3><br />

<%= form_for [@category, @business] do |f| %>
  <div class="form-group">
    <%= f.label 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label 'Address' %>
    <%= f.text_field :address %>
  </div>

  <div class="form-group">
    <%= f.label 'Website' %>
    <%= f.text_field :website %>
  </div>

  <div class="form-group">
    <%= f.label 'Hours' %>
    <%= f.text_field :hours %>
  </div>
  <%= f.submit :class => 'btn btn-info' %>
<% end %>

app/views/businesses/new.html.erb
<h3>New Business</h3>

<%= form_for [@category, @business] do |f| %>
  <div class="form-group">
    <%= f.label 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label 'Address' %>
    <%= f.text_field :address %>
  </div>

  <div class="form-group">
    <%= f.label 'Website' %>
    <%= f.text_field :website %>
  </div>

  <div class="form-group">
    <%= f.label 'Phone Number 1' %>
    <input type="textbox" name="[phones][]"

  </div>

  <div class="form-group">
    <%= f.label 'Phone Number 2' %>
    <input type="textbox" name="[phones][]"
  </div>

  <div class="form-group">
    <%= f.label 'Hours' %>
    <%= f.text_field :hours %>
  </div>
  <%= f.submit :class => 'btn btn-info' %>
<% end %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>

<h3>Address:</h3> <h4><%= @business.address %></h4>
<h3>Website:</h3> <h4><%= @business.website %></h4>
<h3>Phone Numbers:</h3>
<% @business.phones.each do |phone| %>
  <li><h4><%= phone %></h4></li>
<% end %>
<h3>Hours:</h3> <h4><%= @business.hours %></h4>

<%= link_to 'Delete', category_business_path( @category, @business),
                       :data => {:method => 'delete', :confirm => 'Are you sure you want to delete?'} %> |
<%= link_to 'Edit', edit_category_business_path(@category, @business) %>

app/views/categories/edit.html.erb
<h3>Edit category</h3>
<div class="well">

  <%= form_for @category do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
    <%= f.submit :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul class="list-unstyled">
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

<%= link_to "Add a new category", new_category_path %>

app/views/categories/new.html.erb
  <h3>New category</h3>
<div class="well">

    <%= form_for @category do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
      <%= f.submit :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% if @category.businesses.any? %>
  <ul class="business-list list-unstyled">
    <% @category.businesses.each do |business| %>
      <li><%= link_to business.name, category_business_path(@category, business) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no businesses.</p>
<% end %>


<%= link_to 'Add Business', new_category_business_path(@category) %> |
<%= link_to 'Edit', edit_category_path %> |
<%= link_to 'Delete', category_path(@category),
  :data => {:method => 'delete', :confirm => "are you sure?"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img class="logo-img" src="/images/wiki_logo.jpg"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav special-color">
            <li><%= link_to 'Category', categories_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>